<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_ESTOP_RESET" Id="{47ccba85-8c57-43fd-bb31-743461d2d675}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ESTOP_RESET
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_ESTOP_RESET">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>